### ISSUE TITLE
实测播放不了

### ISSUE THREAD

**Issue by llzzxx** [1715173329/CQCU-IPTV#2]
在恩山上找了个源倒是能播了#EXTM3U
#EXTINF:-1,CCTV-1高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000231
#EXTINF:-1,CCTV-2高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000295
#EXTINF:-1,CCTV-3高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000302
#EXTINF:-1,CCTV-4高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000342
#EXTINF:-1,CCTV-5高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000304
#EXTINF:-1,CCTV-6高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000305
#EXTINF:-1,CCTV-7高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000290
#EXTINF:-1,CCTV-8高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000307
#EXTINF:-1,CCTV-9高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000294
#EXTINF:-1,CCTV-10高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000293
#EXTINF:-1,CCTV-11
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000220
#EXTINF:-1,CCTV-12高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000292
#EXTINF:-1,CCTV-13
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000217
#EXTINF:-1,CCTV-14少儿高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000291
#EXTINF:-1,CCTV-15
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000216
#EXTINF:-1,CCTV-17高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000346
#EXTINF:-1,重庆卫视超高清
rtsp://123.147.112.17:8089/04000001/01000000004000000000000000000365
#EXTINF:-1,重庆新闻超高清

**Comment by 1715173329** [comment]
自己替换下 ip 地址和端口就行了，我这里两个都能看。

**Comment by llzzxx** [comment]
> 自己替换下 ip 地址和端口就行了，我这里两个都能看。

Yes，it works now。 THX
